// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9DTarVzJ-uTmH2uocRCWhcmWSkSHiY1Y',
    appId: '1:1064474608117:web:afe3c31fe680612efee0bc',
    messagingSenderId: '1064474608117',
    projectId: 'asu-carpool-20306',
    authDomain: 'asu-carpool-20306.firebaseapp.com',
    databaseURL: 'https://asu-carpool-20306-default-rtdb.firebaseio.com',
    storageBucket: 'asu-carpool-20306.appspot.com',
    measurementId: 'G-Y8PSHYJN7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgJrn2TWJj6E-R0av-Vm1s38H8enPGvUI',
    appId: '1:1064474608117:android:dba0afa8b0d0c9b6fee0bc',
    messagingSenderId: '1064474608117',
    projectId: 'asu-carpool-20306',
    databaseURL: 'https://asu-carpool-20306-default-rtdb.firebaseio.com',
    storageBucket: 'asu-carpool-20306.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9dU1y8B1XeR1hTHiTWYiOlZZBxCbZYCQ',
    appId: '1:1064474608117:ios:ca230cb6b1289b50fee0bc',
    messagingSenderId: '1064474608117',
    projectId: 'asu-carpool-20306',
    databaseURL: 'https://asu-carpool-20306-default-rtdb.firebaseio.com',
    storageBucket: 'asu-carpool-20306.appspot.com',
    iosBundleId: 'com.example.carPool1Driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9dU1y8B1XeR1hTHiTWYiOlZZBxCbZYCQ',
    appId: '1:1064474608117:ios:4a43794267d0bdb7fee0bc',
    messagingSenderId: '1064474608117',
    projectId: 'asu-carpool-20306',
    databaseURL: 'https://asu-carpool-20306-default-rtdb.firebaseio.com',
    storageBucket: 'asu-carpool-20306.appspot.com',
    iosBundleId: 'com.example.carPool1Driver.RunnerTests',
  );
}
